import type { WorkType } from "@/lib/v1";

/**
 * Open roles a candidate can browse and interview for. Illustrative pool today;
 * swaps to v1.listOpeningFits() when the backend is live. Company identity stays
 * an archetype until a consented intro — never the real name up front.
 *
 * `readiness` is requirement COVERAGE, never selection odds. `topGap` is the one
 * thing to close first. The interview a candidate takes is generated by the AI
 * from the employer's role data (role-DNA), so questions adapt to each role.
 */
export interface OpenRole {
  id: string;
  title: string;
  company: string; // archetype, not identity
  workType: WorkType;
  location: string;
  readiness: number; // 0–100 coverage of the role's public requirements
  skills: string[];
  topGap: string;
  fresh?: boolean;
}

export const OPEN_ROLES: readonly OpenRole[] = [
  { id: "op-1", title: "Backend Engineer", company: "A Series-B fintech", workType: "full_time", location: "Bengaluru · Hybrid", readiness: 82, skills: ["Backend systems", "API design", "Production debugging"], topGap: "Kubernetes ownership", fresh: true },
  { id: "op-2", title: "Platform Engineer", company: "A platform-tooling startup", workType: "contract", location: "Remote · India", readiness: 76, skills: ["System design", "IaC / Terraform", "Observability"], topGap: "Terraform depth" },
  { id: "op-3", title: "Junior SRE", company: "A logistics scale-up", workType: "full_time", location: "Pune · On-site", readiness: 61, skills: ["Incident response", "Linux", "Monitoring"], topGap: "SLOs & error budgets" },
  { id: "op-4", title: "Frontend Engineer", company: "A D2C commerce brand", workType: "full_time", location: "Remote · India", readiness: 74, skills: ["Frontend execution", "React", "Product sense"], topGap: "Performance budgets" },
  { id: "op-5", title: "Data Engineer", company: "A health-tech company", workType: "full_time", location: "Hyderabad · Hybrid", readiness: 69, skills: ["Data pipelines", "SQL", "Airflow"], topGap: "Streaming (Kafka)", fresh: true },
  { id: "op-6", title: "Full-stack Engineer", company: "An early-stage AI startup", workType: "full_time", location: "Remote", readiness: 71, skills: ["Backend systems", "Frontend execution", "API design"], topGap: "System design at scale" },
  { id: "op-7", title: "Applied AI Engineer", company: "A global capability centre", workType: "full_time", location: "Bengaluru · Hybrid", readiness: 58, skills: ["Python", "Evaluation", "ML foundations"], topGap: "Production ML" },
];

export const WORK_FILTERS: { id: "all" | WorkType; label: string }[] = [
  { id: "all", label: "All roles" },
  { id: "full_time", label: "Full-time" },
  { id: "contract", label: "Contract" },
];
