import { GraduationCap, Award, ClipboardCheck, Landmark, BookMarked, Clock, ExternalLink } from "lucide-react";
import type { LearningStep, LearningKind } from "@/lib/v1";

const KIND_META: Record<LearningKind, { label: string; Icon: typeof GraduationCap }> = {
  course: { label: "Course", Icon: GraduationCap },
  certification: { label: "Certification", Icon: Award },
  exam: { label: "Exam", Icon: ClipboardCheck },
  program: { label: "Program", Icon: BookMarked },
  college: { label: "College", Icon: Landmark },
};

/**
 * One curated learning step. Always shows its `source` catalog citation —
 * these are curated mappings, never free-generated by an AI.
 */
export function LearningStepRow({ step }: { step: LearningStep }) {
  const { label, Icon } = KIND_META[step.kind];
  const title = (
    <span className="text-[13.5px] font-bold text-[var(--ink)]">
      {step.title}
      {step.url && <ExternalLink size={12} className="ml-1 inline-block align-[-1px] text-[var(--ink-3)]" aria-hidden />}
    </span>
  );

  return (
    <li
      className="group/step flex items-start gap-3 rounded-[14px] border px-3.5 py-3 transition-colors duration-[var(--d-std)] hover:border-[var(--iris-line)]"
      style={{ borderColor: "var(--glass-line)", background: "var(--glass)" }}
    >
      <span
        className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-[10px] text-[var(--iris-ink)] transition-transform duration-[var(--d-std)] group-hover/step:scale-105"
        style={{ background: "var(--iris-ghost)" }}
        aria-hidden
      >
        <Icon size={15} />
      </span>
      <div className="min-w-0 flex-1">
        <p className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5">
          {step.url ? (
            <a href={step.url} target="_blank" rel="noopener noreferrer" className="hover:text-[var(--iris-ink)]">
              {title}
            </a>
          ) : (
            title
          )}
          <span className="text-[11px] font-semibold uppercase tracking-wide text-[var(--ink-3)]">{label}</span>
        </p>
        <p className="mt-0.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-[12px] text-[var(--ink-2)]">
          <span>{step.provider}</span>
          {step.est_effort && (
            <span className="inline-flex items-center gap-1 text-[var(--ink-3)]">
              <Clock size={11} aria-hidden /> {step.est_effort}
            </span>
          )}
        </p>
      </div>
      <span
        className="mt-0.5 hidden shrink-0 rounded-full border px-2 py-0.5 text-[10px] font-medium text-[var(--ink-3)] sm:inline-block"
        style={{ borderColor: "var(--glass-line)", fontFamily: "var(--font-mono)" }}
        title="Catalog citation — this recommendation is curated, not AI-invented"
      >
        {step.source}
      </span>
    </li>
  );
}
